WITH TOTAL_SCORE AS (
    SELECT SUM(G.SCORE) AS SCORE,
           G.EMP_NO,
           E.EMP_NAME,
           E.POSITION,
           E.EMAIL
    FROM HR_GRADE G
    LEFT JOIN HR_EMPLOYEES E
      ON G.EMP_NO = E.EMP_NO
    WHERE G.YEAR = 2022
    GROUP BY G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
)
SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM TOTAL_SCORE
WHERE SCORE = (SELECT MAX(SCORE) FROM TOTAL_SCORE)
ORDER BY EMP_NO;